<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="../../src/CommerceMcpDemo.Application/CommerceMcpDemo.Application.csproj" />
    <ProjectReference Include="../../src/CommerceMcpDemo.Infrastructure/CommerceMcpDemo.Infrastructure.csproj" />
    <ProjectReference Include="../../src/CommerceMcpDemo.McpServer/CommerceMcpDemo.McpServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../src/CommerceMcpDemo.McpServer/tools.json" Link="tools.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
